#spring.application.name=ElectronixExpress
#server.port=9090
  
#db configurations
#spring.datasource.url=jdbc:mysql://localhost:3306/electronix_express
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
  
#jpa configurations
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
spring:
  application:
    name: ElectronixExpress
  datasource:
    url: jdbc:mysql://localhost:3306/electronix_express
    username: root
    password: ziamysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
user:
  profile:
    image-path: images/users/
category:
  image-path: images/category/
product:
  image-path: images/products/